# Generated by Django 3.1.5 on 2021-01-12 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPessoa',
            fields=[
                ('CPF', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('lista_dividas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.SmallIntegerField()),
                ('lista_bens', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('fonte_renda', models.CharField(max_length=255)),
                ('CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultapessoa')),
            ],
        ),
        migrations.CreateModel(
            name='RastreaEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_consulta_cpf', models.DateTimeField(auto_now_add=True)),
                ('movimentacao_financeira', models.FloatField()),
                ('dados_relacionados', models.CharField(max_length=255)),
                ('CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultapessoa')),
            ],
        ),
    ]
